### ISSUE TITLE
Error during kubernetes cluster installation

### ISSUE THREAD

**Issue by bushmaster570** [omerbsezer/Fast-Kubernetes#3]
I am getting this error during installation:

```
ubuntu@master:~$ sudo kubeadm config images pull
failed to pull image "registry.k8s.io/kube-apiserver:v1.26.1": output: time="2023-02-14T11:21:55+05:00" level=fatal msg="validate service connection: CRI v1 image API is not implemented for endpoint \"unix:///var/run/containerd/containerd.sock\": rpc error: code = Unimplemented desc = unknown service runtime.v1.ImageService"
, error: exit status 1
To see the stack trace of this error execute with --v=5 or higher
```

**Comment by omerbsezer** [comment]
Please download 
install.sh: https://github.com/omerbsezer/Fast-Kubernetes/blob/main/install.sh 
master.sh: https://github.com/omerbsezer/Fast-Kubernetes/blob/main/master.sh

chmod 777 install.sh
./install.sh
chmod 777 master.sh
./master.sh [MasterNodeIP]

If your PC is not behind the Proxy Server, it will work. I run install.sh. It works on my PC (in multipass):
![image](https://user-images.githubusercontent.com/10358317/220177941-2ea07981-58bc-43e1-a425-b2834ea64d68.png)
